import type { SpriteDef } from './PixelArtGenerator';

/**
 * Boss v3 — redessinés d'après les références visuelles (Boss Fights v3).
 * Chaque boss a SA silhouette (aucune forme partagée), plus grande que le héros,
 * avec un attribut surdimensionné lisible en ombre chinoise, et la palette
 * hexadécimale officielle du document de production. Orientés vers la droite
 * (ou de face quand la référence l'est) ; le miroir gauche est géré au rendu.
 */

/** Sylvaan — Centaure Sylvestre (34×39) : profil 3/4 à droite, bois de cerf
 * ramifiés, torse de bois clair, robe équine d'écorce, crinière et queue de
 * feuillage, arc de bois vivant tenu bras tendu. */
export const BOSS_CENTAURE: SpriteDef = {
  key: 'boss_centaure',
  pal: {
    '.': null, '#': '#2e1e10', 'a': '#8a6a3f', 'A': '#b89058', 'o': '#6a4a2a',
    's': '#d8b878', 'S': '#a8845a', 'e': '#5fd06a',
    'w': '#c89b5a', 'W': '#8b6534', 'k': '#5a3e1e',
    'g': '#7db84a', 'G': '#4f8f3f', 'd': '#2f5f2f', 'h': '#d8cfa8',
  },
  rows: [
    '..................#AaA#....#AaA#..',
    '...................#aA#....#Aa#...',
    '....................##A##.#A##....',
    '...................#.#A#s##A#.....',
    '..................#d##sAsSA#......',
    '...................#gsssSSSS#.....',
    '....................#GsSS#ee##....',
    '..................##ssSSSSesss#...',
    '.................#dGgSSSSSkssS#...',
    '.................##GGGGGGGkk##....',
    '................#dgdddddddk#......',
    '...............#gggggdGgkSS#......',
    '..............#dGGGGGddGgSS#......',
    '...............####ssSWdGgSk#.##..',
    '.......###.........#sSWSSSSk##oo#.',
    '......#dgd####.#...#SSWSSSkSk##o#.',
    '.....#gggggdgd#w####SSWSSSkSk##o#.',
    '...##dGGGGGgggwwwwwWWSWSSS##Sk#o#.',
    '..#dgd#wwwdGGGdwwWkWWSSSSS##Sk#o#.',
    '.#gggwkwwwkwwwkWWWkWWWkkWW#.#w#o#.',
    '#dGGwwkwwwkwwWkWWWkWWWkWWWW##Woo#.',
    '.###wwkwwwkWWWkWWWkWWWkWWWk#.###..',
    '.#dwwwkwwWkWWWkWWWkWWWkWkkkk#.....',
    '#gggwwkWWWkWWWkWWWkWWWkkkkk#......',
    'dGGGwWkWWWkWWWkWWWkWWWkkWWk#......',
    '###dGWkWWWkWWWkWWWkkWWkkWW#.......',
    '.#dGg##WWWkWWWkWkkkkwWkkwW#.......',
    '.#dGg#.##WWWWWkkkkkkWW##WW#.......',
    '..###...#kk##kkk####WW##WW#.......',
    '........#kk##kk#...#WW##WW#.......',
    '........#Gg##Gg#...#Gg##Gg#.......',
    '........#dk##dk#...#dW##dW#.......',
    '........#kk##kk#...#WW##WW#.......',
    '........#kk##kk#...#WW##WW#.......',
    '........#kk##kk#...#WW##WW#.......',
    '........#hh##hh#...#WW##WW#.......',
    '........#hh##hh#...#hh##hh#.......',
    '.........##..##....#hh##hh#.......',
    '....................##..##........',
  ],
};

/** Gorbak — Bourbier Vivant : tas de boue amorphe cornu, large sourire blanc. */
export const BOSS_GOBU: SpriteDef = {
  key: 'boss_gobugeant',
  pal: { '.': null, '#': '#241a0e', 'k': '#3a2c14', 'm': '#5a4a24', 'M': '#7a6636', 'w': '#9a8848', 'W': '#b8a666', 'r': '#d03020', 'R': '#ff5a3a', 'e': '#141008', 'T': '#f4efe0' },
  rows: [
    '............................##..',
    '...........................#kM#.',
    '.....##...................#kM#..',
    '....#km#..................#kM#..',
    '.....#km#................#kM#...',
    '.....#km#.......#........#kM#...',
    '......#km#.#####W#####..#kM#....',
    '......#km##WWWWWWWWWWM###kM#....',
    '.......##WWWWWWWWWWWMMMM###.....',
    '......#WWWWWWWWWWWMMMMMMMM#.....',
    '.....#WWWWWWWWWWWMMMMMMMMMM#....',
    '....#WWWWWWWWWWWwMMMMMMMMMMM#...',
    '....#WWWWWeeeewwwweeeeeMMMMM#...',
    '...#WWWWWwRrrrwwwwRrrrrmMMMMM#..',
    '...#WWWWwwrrrRwwwmrrrrrmmMMMk#..',
    '...#WWWwwwwwwwwwmmrrrrRmmmMkk#..',
    '..#WWWwwwwwwwwwmmmmmmmmmmmmkkk#.',
    '...#WWwwwwwwwmmmmmmmmmmmmmmkk#..',
    '...#WWwwwwTwmmmmmmmmmTmmmmkkk#..',
    '...#WwwwwwmTTTTTTTTTTTmmkkkkk#..',
    '....#Mwwwmmememememememkkkkk#...',
    '....#Mwwmmmmmmmmmmmmmkkkkkkk#...',
    '.....#mmmmmmmmmmmmmmkkkkkkk##...',
    '......#mkmmmmkmmmmmkkkkkkk##k#..',
    '.......#kmmmmkmmmkkkkkkkk#.#k#..',
    '.......#kmmmmkmmkkkkkkkkk#.#k#..',
    '.......#k##mmkmkkkkkkk##k#.#k#..',
    '........#..#####k#####..#...#...',
    '................#...............',
  ],
};

/** Ignis — Dragon de Lave : bipède ailé, ventre-fournaise, ailes de feu (de face). */
export const BOSS_SERPENT: SpriteDef = {
  key: 'boss_serpentlave',
  pal: { '.': null, '#': '#2a0f06', 'b': '#241009', 'k': '#3a1a10', 'r': '#7a2a10', 'o': '#c9500f', 'H': '#ff6a1f', 'O': '#ffb020', 'y': '#ffe08a', 'w': '#a83010', 'W': '#ff8a2a' },
  rows: [
    '............#.......#...........',
    '...........#r#.....#r#..........',
    '...........#k#.....#k#..........',
    '......#.....#k#.#.#k#....#......',
    '.....#O#.....###k###....#O#.....',
    '.....#r#.....#kkkkk#....#r#.....',
    '....#rHr#...#kkkkkkH#..#rHr#....',
    '...#rHHHr#..#kOykkyO###rHHHr#...',
    '...#rHOHr#.#kkkkkkkkOk#rHOHr#...',
    '..#WrHHHr#..#kkkkkkkkr#rHHHr#...',
    '..#rHHHHHr#.#kkkkkbb##rHHHHHr#..',
    '.#WHrHHHr#..#rkkkkbk#.#rHHHrH#..',
    '.#OwrHHHr#.#rrrkkkkkk##rHHHrwO#.',
    '#WH#rHHHr##rrrrrOkkkkk#rHHHrwH#.',
    '#Ww##rHr##rrrrOOOOokkkk#rHr##wW#',
    '.##..#r###rrrOOOyoookkk##r#..##.',
    '......##kkkkOOOyyyoookkkk#......',
    '.......#kkkkOOyyyyyookkkk#......',
    '.......#kkkkOOyyOyyookkkk#......',
    '.......#kkkkOyyyyyyyrkkkk#......',
    '.......#kkkkOoyyyyyrrkkkk#......',
    '........#ykkooyyyyyrrbby#.......',
    '.........#kkoooyyyrrrbb#........',
    '..........#kkoooyrrrbb#.###.....',
    '..........#kkkoorrrbbk##kkr##...',
    '..........#kkkkbrbbbkk#.##kkr##.',
    '..........#kkkk#b#kkkk#...##kkr#',
    '..........#kkkk###kkkk#.....##HO',
    '..........#kkkk#.#kkkk#.......##',
    '..........#kkkk#.#kkkk#.........',
    '..........#kkkk#.#kkkk#.........',
    '..........#yyyy#.#yyyy#.........',
  ],
};

/** Mortis — Dracoliche Archimage : chapeau immense, crâne, robe en lambeaux, bâton. */
export const BOSS_ARCHIMAGE: SpriteDef = {
  key: 'boss_archimage',
  pal: { '.': null, '#': '#0e0b1a', 'k': '#1a1428', 'p': '#3a2c5a', 'P': '#4a2c7a', 'v': '#5a3a8a', 'B': '#241a3a', 'g': '#c9a23a', 'y': '#f4c430', 'W': '#e6e2d4', 'w': '#b8b0a0', 'e': '#c78aff', 'f': '#8a5cff', 'r': '#7a2436', 'R': '#a83048' },
  rows: [
    '.......#vvv#..#v#...#p#.......',
    '......#vvvvv#..#...#p#........',
    '.......#vvvp#.....#p#.........',
    '........#v##p###.#p#..........',
    '.........#..#pyy#p#...........',
    '.........#####pWp#####........',
    '....#...#PPPPPPPPPPPPP#.......',
    '....##.#ppppppppppppppp##.....',
    '....#P##ppppppppppppppp#P#....',
    '...#epP####WWewwwwkk###PpP#...',
    '..#PfppP#..#wwwwwkk#.#PpppP#..',
    '..#P#ppP#..#wwwWWWW#.#PpppP#..',
    '..#PWppP#...#wwWWWW#.#PpppP#..',
    '.#R#W#pP#...#WWWWWW#.#PpppP#..',
    '.#WWWWWpP#...######.#PpppppP#.',
    '#RrWWWpP##..###v###..#PpppPR#.',
    '#RrPWppppp##vvvvvvP#.#PpppPrR#',
    'Rr#P#ppppp#vvvvvvPPP##PpppPrR#',
    'Rr#P#pppppvPPPPPPPPPP#PpppP#rR',
    'r#.##pppppvPPPPPPPPPP##PpP##rR',
    'r#..#PppppvPPPPPPPPPPP##P#..#r',
    '#...##ppppvPPPPPPPPPPP#.#....#',
    '....##ppppvPPPPyPPPPPP#.......',
    '....##ppppvPPPPPPPPPPB#.......',
    '....##ppppvPPyPgPyPPBBB#......',
    '....#.###vvPPPPPPPPPBB#.......',
    '........#vPPPPPyPPPPBB#.......',
    '........#PPPPPPPPPPPBB#.......',
    '........#PPPPPPPPPPPBB#.......',
    '.........#PPPPPPPPPPB#........',
    '.........#PPPPPPPPPPB#........',
    '..........#PPPPBBBBB#.........',
    '...........#PPBBBBB#..........',
    '............###B###...........',
    '...............#..............',
  ],
};

/** Glacior — Léviathan des Abysses : serpent de glace LOVÉ, crête en couronne. */
export const BOSS_LEVIATHAN: SpriteDef = {
  key: 'boss_leviathan',
  pal: { '.': null, '#': '#0a1420', 'i': '#123a54', 'k': '#14283a', 'm': '#2a4a60', 'r': '#3a6a8a', 'w': '#a8c8e0', 'W': '#dcecf8', 'C': '#9fe0f8', 'H': '#7fdcff', 'e': '#e8f8ff' },
  rows: [
    '..#e#e#e#e#.....................',
    '..#H#H#H#H#.....................',
    '...###W###......................',
    '..#CWWWww#......................',
    '.#HWWWH#ww#.....................',
    '.#wwwwewwrr#....................',
    '#rwwwwwwrr#.....................',
    '.###wwwrr#......................',
    '....#wrr#.......................',
    '.....#wWr#......................',
    '.....#wWr#......................',
    '......#wWr#.....................',
    '......#wWr#.....................',
    '.......#wWr#....................',
    '.......#wWr#....................',
    '......#.#wWr#..#..#..#..#.......',
    '.....#e##wWre##e##e##e##e#......',
    '.....#H##H##H##H##H##H##H#......',
    '.....#C##C##C##CW#C##C##C#......',
    '......####WWWWWWWWWWrrr###......',
    '......#WWWWWWWWWWWWrrrrrrr#.....',
    '.....#WWWWWWWWWWkrrrrrrrrrr#....',
    '....#WWWWWWkkkkk#kkkkkrrrrrr#...',
    '...#WWWWWkk#####.#####kkrrrrr#..',
    '...#WWWWk##...........##krrkk#..',
    '..#WWWWk#...............#kkkkk#.',
    '...#WWWrk##...........##kkkkk#..',
    '...#WWrrrkk#####.#####kkkkkkk#..',
    '....#rrrrrrkkkkk#kkkkkkkkkkk#...',
    '.....#rrrrrrrrrrkrkkkkkkkkk#....',
    '......#rrrrrrrrrkkkkkkkkkk#.....',
    '.......###rrrrkkkkkkkkk###......',
    '..........######k######.........',
    '................#...............',
  ],
};

/** Voltaïr — Panda-Tonnerre : quadrupède caparaçonné + nuage d'orage, éclairs. */
export const BOSS_RAPACE: SpriteDef = {
  key: 'boss_rapace',
  pal: { '.': null, '#': '#0c0c16', 'k': '#141422', 'W': '#f0f0f8', 'w': '#c8c8d8', 'p': '#7a4ad0', 'P': '#9a6ae8', 'g': '#e0b83a', 'y': '#ffe066', 'L': '#fff2a0', 'B': '#8ab8ff', 'b': '#3a6ad0', 'e': '#ffd24a' },
  rows: [
    '............##pPyPp##...........',
    '...........#ppPPPPPpp#..........',
    '..........##pPpPPPpPp##.........',
    '.........#ppPpppPpppPpp#........',
    '.........#pPPPpPpPpPPPp#........',
    '........#pPPPPPpppPPPPPp#.......',
    '......#..#pPPPp###pPPPp#........',
    '.....#k#.#ppkpp#.#ppPpp#........',
    '....#kkk###kkk#...##p##.........',
    '...#kkkkkWkkkkk#....#...........',
    '....#kkkWWWkkk#.................',
    '....#ggggBgggg#.................',
    '..#.#WWkWWWkWW#.................',
    '.#B##WkkkWkkkW#.....#...........',
    '#b##Wkkekkkykkw#####W####.......',
    '.#B##WkkkWkkkw##WWWWWWWww###....',
    '..#B#WWkWWWkwwWWWWWWWWWWWWWW#...',
    '...##WWkkkkwwwWWWWWWWWWWWWWW#...',
    '.....#WkBkkwwWWWWWWWyWWWWWWW#...',
    '......###w###WWWgggggggggWWW#...',
    '.........#.#WWWWWWWWWyWWWWWWk#..',
    '............#WWWWWWWWWWWWWWW#...',
    '............#WWWWWWWWWWWWWWW#...',
    '............#WWWWWWWWWWWWWWW#...',
    '...........#kkkkWWWWWWWWkkkk#...',
    '...........#kkkkwwkkkkkkkkkk#...',
    '...........#kkkk##kkkk##kkkk#...',
    '...........#kkkk##kkkk##kkkk#...',
    '...........#kkkk##kkkk##kkkk#...',
    '...........#kkkk##kkkk##kkkk#...',
    '...........#kkkk##kkkk##kkkk#...',
    '...........#WWWW#.####.#WWWW#...',
  ],
};

/** Néantis — Roi du Néant : rongeur royal doré, spirale de vide ventrale, épée du vide. */
export const BOSS_REFLET: SpriteDef = {
  key: 'boss_reflet',
  pal: { '.': null, '#': '#0a0612', 'k': '#141021', 'g': '#c99a2a', 'G': '#e0b83a', 'y': '#ffe066', 'p': '#7a2ad0', 'P': '#b060ff', 'v': '#4a1a8a', 'W': '#f0e6c8', 'w': '#c8b890', 'e': '#e0a0ff', 'b': '#241830' },
  rows: [
    '..........#.#..#..#GGG#.......',
    '.........#G#y##y##yGGG#.......',
    '........#GGGG##G##GGGGG#......',
    '........#GGGGGGPGGGGGG#.......',
    '.......#GGGGGGGGGGGGGG#.......',
    '........#GGGGGGGGggGGG#.......',
    '........#GGGGGGGggggG#........',
    '.........#GGGGGgggPg#.........',
    '..........#GPegggPeg#.........',
    '.........#GGGggggggbb#........',
    '.........##Gggggggbb##........',
    '.......##vvgggwwwbbbbb##......',
    '......#vvvvgggw#wbbbbbbb#.....',
    '....##vvvvvvvvvvvvvvvbbbb#....',
    '...#evvvvvpppppWpppppbbbbb#...',
    '..#PpPvvvvvvWWWWWwwbbbbbbb#...',
    '...#pvggggvWWWWWwwwwbbbbbbb#..',
    '...#pvggggvWWWWWwwwwbbbbbbb#..',
    '...#pvggggWWWWWPwwwwwbbbbbk#..',
    '...#pvggggWWWpwwwpwwwbbbbkk#..',
    '..#vpvggggWWWwwwwwwwwbbbkkkk#.',
    '...#vvggggWWPwwvPwPwkkbkkkk#..',
    '...#vvggggWwwwwwwwwkkbkkkkk#..',
    '...#vvbwbbwwwpwwwpkkkkkkkkk#..',
    '...#vbbbbbwwwwwPwkkkkkkkkkk#..',
    '....#bbbbbbwwwwwkkkkkkkkkk#...',
    '....#bbbbbbwwwwkkkkkkkkkkk#...',
    '.....#bbbbbbwwwkkkkkkkkkk#....',
    '......#bbbbbbbbkkkkkkkkk#.....',
    '.......##bbggggkggggkk##......',
    '.........##ggggkgggg##........',
    '..........#ggggkgggg#.........',
    '..........#gggg#gggg#.........',
    '...........####.####..........',
  ],
};

/** Général Kaptain Miaou — boss final : chat militaire (béret, cache-œil, treillis camo). */
export const BOSS_MILITAIRE: SpriteDef = {
  key: 'boss_militaire',
  pal: {
    '.': null, '#': '#0a0e08', 'b': '#2e5a2e', 'B': '#3f7a3f', 'f': '#8a8f86', 'F': '#b8beb0',
    'k': '#141414', 'y': '#ffd24a', 'r': '#d0402a', 'm': '#6a7078', 'c': '#3a4a28', 'C': '#5a6a38', 'v': '#7a8a4a',
  },
  rows: [
    '..............................',
    '.........#########..#.........',
    '........#BBBBBBBBb##f#........',
    '.......#BBBBBBBBBBbbfk#.......',
    '......#bBBBBrmBBBBbbbB#.......',
    '......#bbBBBBBBBBbbbbff###....',
    '......#fbbbbbbbbbbbbFFffkk#...',
    '.......#fFbbbbbbbbFfFF##k#....',
    '......#fffFfFFFFFFFfffkk#.....',
    '......#ffFFFfFFFFFfFkkf#......',
    '......#fFFyyFFFFkkkkkFf#......',
    '......#fFyyyyFFFkkkkkFf#......',
    '......#fFyy#yFFFkkkkkkf#......',
    '......#fFFyyFFFFkkkkkkf#......',
    '......#fFFFFFFFFkkkkkFk#......',
    '......#fFFrFFFFFFFFFFFk##.....',
    '.......#fFFrFFF#FFFFFf#kk#....',
    '........#fFFFFFFFFFFfk##k#....',
    '.....###ccfFFFFFFFFfkc###k#...',
    '....#CC#cCCCffFFffkCCc#CCk#...',
    '...#CCCCCCCCCCCCkkCyCCCCCC#...',
    '...#CCCCCCCCCCCkvyCCCCCCCC#...',
    '..#CCCCCCCCvCCkyCCCCCvCCCCC#..',
    '..#CCCCCCCCCkyCCCCCCCCCCCCC#..',
    '...#CCCCCvCyCCCCCCCCCCCCCC#...',
    '..#ffffCCykCCCCCCCCvCCCffff#..',
    '..#ffffckCCCvCCCCCCCCccffff#..',
    '..#ffffcccCCCCCCCCCCcccffff#..',
    '..#ffff#cccCCCvCCCCccc#ffff#..',
    '...#####cccccccccccccc#####...',
    '........#ccccccccccccc#.......',
    '........#ccccccccccccc#.......',
    '........#kkkk#####kkkk#.......',
    '........#kkkk#...#kkkk#.......',
  ],
};

export const BOSS_CATS: SpriteDef[] = [
  BOSS_CENTAURE, BOSS_GOBU, BOSS_SERPENT, BOSS_ARCHIMAGE,
  BOSS_LEVIATHAN, BOSS_RAPACE, BOSS_REFLET, BOSS_MILITAIRE,
];
