/** Petits dialogues chaton ↔ boss joués avant chaque combat (tirés au hasard). */
export interface Taunt { cat: string; boss: string; }

export const BOSS_TAUNTS: Record<string, Taunt[]> = {
  // Sylvaan — Centaure Archer (Forêt)
  araignee: [
    { cat: 'Tu vises bien… pour un poney à bois.', boss: 'Je vais te clouer au sol, matou !' },
    { cat: 'Belles cornes ! Ça sert de porte-manteau ?', boss: 'Insolent ! Mes flèches te feront ronronner de douleur.' },
    { cat: 'J’ai laissé mes croquettes au chaud, finissons vite.', boss: 'La forêt sera ton tombeau, petit chat.' },
    { cat: 'Un centaure-chat ? On se ressemble presque.', boss: 'Ne me compare pas à toi, boule de poils !' },
    { cat: 'Mi-cheval, mi-chat… t’as pris quoi au petit-déj ?', boss: 'Assez ! Encoche, vise, adieu.' },
    { cat: 'Tir à l’arc ? J’ai mon revers, ça ira.', boss: 'Aucune flèche ne me manque. Aucune.' },
    { cat: 'Tu galopes ou tu tires ? Faut choisir.', boss: 'Je fais les deux, et je t’enterre entre.' },
    { cat: 'Sylvaan… ça rime avec « je vais gagner ».', boss: 'Ça rime surtout avec ton dernier souffle.' },
    { cat: 'Les druides, c’est ton service après-vente ?', boss: 'Mes druides te soigneront… juste pour recommencer.' },
    { cat: 'Joli carquois. Très vintage.', boss: 'Mille ans, mille victimes. Tu seras la suivante.' },
    { cat: 'Un sabot dans la truffe, ça se soigne ?', boss: 'Pas là où tu vas, chaton.' },
    { cat: 'La forêt te protège ? Elle a mauvais goût.', boss: 'Chaque arbre ici a vu tomber un héros.' },
    { cat: 'Tu sens le foin et l’orgueil.', boss: 'Et toi la peur. Elle est délicieuse.' },
    { cat: 'Encoche, vise, rate. On répète ?', boss: 'Je ne rate jamais deux fois.' },
    { cat: 'Bang ! …pardon, je m’entraîne.', boss: 'Garde tes forces. Tu vas courir.' },
  ],
  // Gorbak — Gobu Géant (Marais)
  crapaudroi: [
    { cat: 'Ça sent le fromage oublié… c’est toi ?', boss: 'GORBAK écrase le petit chat !' },
    { cat: 'T’as pris un bain de boue ? Très classe.', boss: 'Gorbak va te rouler dessus. SPLATCH !' },
    { cat: 'Gros mais lent : mon combo préféré.', boss: 'Grrr… Gorbak PAS lent ! Gorbak SMASH !' },
    { cat: 'Tu craches vraiment partout, quelle éducation.', boss: 'Gorbak faim. Gorbak mange chaton.' },
    { cat: 'Gorbak connaît d’autres mots que « Gorbak » ?', boss: 'Gorbak connaît : ÉCRASER.' },
    { cat: 'T’as mangé quoi ? Un marécage entier ?', boss: 'Gorbak mange TOUT. Bientôt chaton.' },
    { cat: 'Attention, tu dégoulines sur mon armure.', boss: 'Gorbak fait pipi de boue sur chaton !' },
    { cat: 'Roule pas trop vite, tu vas vomir.', boss: 'Gorbak roule, chaton craque !' },
    { cat: 'T’as un mouchoir ? Non ? Tant pis.', boss: 'Gorbak pas besoin. Gorbak crache !' },
    { cat: 'Mini-Gorbak, maxi-problème, je sais.', boss: 'Gorbak fait bébés. Bébés font boum.' },
    { cat: 'Deux neurones et beaucoup de bave.', boss: 'Gorbak PAS bête ! Gorbak… euh… SMASH !' },
    { cat: 'Le marais pue autant que tes vannes.', boss: 'Gorbak aime pue. Chaton va aimer aussi.' },
    { cat: 'Tu tapes fort mais tu vises mal.', boss: 'Gorbak tape PARTOUT. Une touche.' },
    { cat: 'Fais-moi un câlin, gros bêta.', boss: 'Gorbak câlin = os cassé !' },
  ],
  // Ignis — Serpent de Lave (Forge)
  golem: [
    { cat: 'Un serpent de lave ? J’espère que t’as pas froid.', boss: 'Tu vas fondre, misérable félin.' },
    { cat: 'Sssuper, un chauffage ambulant.', boss: 'Ssssilence ! Mes flammes te réduiront en cendres.' },
    { cat: 'Je préfère les serpentins de fête, sans rancune.', boss: 'Ta toute dernière plaisanterie, chaton.' },
    { cat: 'Tu mues souvent ? J’ai le même souci avec les poils.', boss: 'Rampe hors de mon antre… ou brûle.' },
    { cat: 'Tu chauffes la pièce, c’est sympa.', boss: 'Je la transformerai en ton bûcher.' },
    { cat: 'Sssalut. Ça va les écailles ?', boss: 'Ellesss survivront à toi, sssûrement.' },
    { cat: 'Une tornade de feu ? Original.', boss: 'Cinq. Elles viennent de partout. Danssse.' },
    { cat: 'J’ai apporté des marshmallows.', boss: 'Tu SERAS le marshmallow, chaton.' },
    { cat: 'La lave, c’est ta couette ?', boss: 'C’est ton linceul, félin.' },
    { cat: 'T’es long pour rien dire.', boss: 'Je siffle. Puis tu brûles. Concisss.' },
    { cat: 'Éteins-toi, je veux dormir.', boss: 'Tu dormiras… en cendres.' },
    { cat: 'Tu laisses des flaques de lave partout.', boss: 'Chacune porte ton nom, chaton.' },
    { cat: 'Serpent plus forge : fondue de chat ?', boss: 'Exactement. Approche du chaudron.' },
    { cat: 'Fais gaffe, je griffe le métal chaud.', boss: 'Et moi je fais fondre la fourrure.' },
  ],
  // Mortis — Archimage Mort-vivant (Citadelle)
  roi: [
    { cat: 'L’archimage… encore debout à cette heure ?', boss: 'Ton âme rejoindra mon armée, chaton.' },
    { cat: 'T’as une tête de déterré. Littéralement.', boss: 'Je danserai sur ta tombe, petit chat.' },
    { cat: 'Invoque ce que tu veux, j’ai neuf vies.', boss: 'Alors je les prendrai… toutes les neuf.' },
    { cat: 'Chapeau pointu, blagues plates.', boss: 'Insolence ! Meurs dans les ombres !' },
    { cat: 'Tu sens le vieux grimoire moisi, tu sais ?', boss: 'Le silence éternel t’apprendra le respect.' },
    { cat: 'T’as pensé à te recoucher, mort-vivant ?', boss: 'Le repos est pour les vivants. Tu vas l’essayer.' },
    { cat: 'Encore des zombies ? Recycle un peu.', boss: 'Ils étaient des héros. Comme toi. Regarde-les.' },
    { cat: 'Tes glyphes brillent joli.', boss: 'Marche dessus, tu verras à quel point.' },
    { cat: 'Téléporte-toi… loin, de préférence.', boss: 'Je réapparais toujours dans ton dos.' },
    { cat: 'Nécromancien cherche âme. Pas la mienne.', boss: 'La tienne fera un excellent serviteur.' },
    { cat: 'Tu invoques mes anciens ennemis ? Radin.', boss: 'Pourquoi créer quand on peut ressusciter ?' },
    { cat: 'T’as une odeur de chapelle abandonnée.', boss: 'Bientôt, ce sera ton parfum éternel.' },
    { cat: 'Neuf vies contre un squelette. J’ai le stock.', boss: 'Je collectionne. Neuf trophées me plaisent.' },
    { cat: 'Baisse la lumière violette, ça pique.', boss: 'C’est la dernière que tes yeux verront.' },
    { cat: 'Alors, on danse ou on se bat ?', boss: 'Sur ta tombe. Les deux.' },
  ],
  // Glacior — Léviathan des Abysses (Abysses de Givre)
  leviathan: [
    { cat: 'Un poisson-chat ? C’est moi qui devrais te manger.', boss: 'Les abysses ont englouti cent héros. Tu feras un amuse-gueule.' },
    { cat: 'J’ai horreur des congélateurs. On m’y a déjà enfermé une fois.', boss: 'Le froid conserve. Je te garderai parfait. Immobile. Éternel.' },
    { cat: 'Ta patinoire est nulle, y’a même pas de musique.', boss: 'Le craquement de la glace SERA ta musique.' },
    { cat: 'J’ai horreur de l’eau froide.', boss: 'Parfait. Tu détesteras chaque seconde.' },
    { cat: 'Un léviathan dans une flaque gelée.', boss: 'Cette flaque a noyé des flottes entières.' },
    { cat: 'Tes stalactites tombent mal.', boss: 'Elles tombent PILE sur toi. Lève les yeux.' },
    { cat: 'Éteins la clim, je gèle.', boss: 'Bientôt tu ne sentiras plus rien du tout.' },
    { cat: 'Poisson-chat contre chat-poisson ?', boss: 'Contre TON reflet figé pour l’éternité.' },
    { cat: 'Tu fais fondre mon moral, pas mes griffes.', boss: 'Je ferai fondre… puis regeler. Lentement.' },
    { cat: 'Tes piliers brillent, ils servent à quoi ?', boss: 'À me rendre invincible. Brise-les si tu oses.' },
    { cat: 'On glisse ! …c’était pas voulu.', boss: 'Rien n’est voulu, ici. Seulement inévitable.' },
    { cat: 'T’aurais un plaid ? Un petit ?', boss: 'J’ai mieux : un cercueil de glace.' },
    { cat: 'Les abysses, c’est humide et déprimant.', boss: 'C’est chez moi. Et ta dernière adresse.' },
  ],
  // Voltaïr — Rapace du Jugement (Nécropole Céleste)
  rapace: [
    { cat: 'Chouette, un poulet géant. J’ai justement faim.', boss: 'Je suis le JUGEMENT. Et le verdict est : coupable d’exister.' },
    { cat: 'Parfait, je comptais pas rester.', boss: 'Cent rois reposent dans ma nécropole. Tu ne mérites même pas une tombe.' },
    { cat: 'Tu juges les gens ? Juge un peu ma lame.', boss: 'L’orage précède toujours la sentence.' },
    { cat: 'Monsieur le juge, je plaide coupable de trop de style.', boss: 'La peine : la mort. Comme d’habitude.' },
    { cat: 'Beau plumage, cerveau d’oiseau ?', boss: 'Assez pour lire ta sentence. Coupable.' },
    { cat: 'L’orage, c’est ton intro dramatique ?', boss: 'C’est le tonnerre de ton verdict.' },
    { cat: 'Tu juges, mais t’as jugé ta coiffure ?', boss: 'Silence dans le tribunal, félin.' },
    { cat: 'Un poulet céleste. Rôti, ce serait mieux.', boss: 'Tes plaisanteries alourdissent ta peine.' },
    { cat: 'La sentence, tu peux la classer ?', boss: 'Elle est déjà exécutée. Tu l’ignores encore.' },
    { cat: 'Cent rois ? T’as juste un gros nid.', boss: 'Un nid d’ossements. Tu compléteras la collection.' },
    { cat: 'J’ai un avocat ? Non ? Bon.', boss: 'Ici, je suis juge, jury et bourreau.' },
    { cat: 'Tu voles haut pour tomber bas.', boss: 'Je fonds sur les coupables. Tu voles où, toi ?' },
    { cat: 'Objection ! …ah, on peut pas.', boss: 'Objection rejetée. Exécution.' },
  ],
  // Néantis — le Reflet Noir (Faille du Néant)
  reflet: [
    { cat: 'Alors t’es pas bien épais.', boss: 'Je suis chaque doute que tu as eu entre deux salles.' },
    { cat: 'Copier mon style, mes pouvoirs, ma tête… T’as pas d’idées à toi ?', boss: 'Pourquoi créer, quand tout finit ici, en moi ?' },
    { cat: 'Parfait. Personne me connaît mieux que moi. Et je me bats mieux que toi.', boss: 'Sept mondes pour finir face à toi-même.' },
    { cat: 'Un miroir qui parle. Flippant.', boss: 'Je suis toi, sans les excuses.' },
    { cat: 'T’imites mal mon charme.', boss: 'J’imite parfaitement ta fin.' },
    { cat: 'Copieur ! Trouve tes propres vannes.', boss: 'Tes vannes sont les miennes, désormais.' },
    { cat: 'On se ressemble mais je sens meilleur.', boss: 'Tu sentiras bientôt le néant.' },
    { cat: 'Deux chatons, un seul survivant ?', boss: 'Zéro, si je choisis. Le vide nous prend tous.' },
    { cat: 'T’as mes pouvoirs mais pas mes tripes.', boss: 'J’ai tes doutes. Ça suffira.' },
    { cat: 'Arrête de me fixer, c’est glauque.', boss: 'Je ne fais que regarder ce que tu deviendras.' },
    { cat: 'Sept mondes pour ça ? Décevant.', boss: 'La destination était toujours toi-même.' },
    { cat: 'On se serre la patte après ?', boss: 'Il ne restera aucune patte à serrer.' },
    { cat: 'Je vais me battre… contre moi. Bizarre.', boss: 'Et perdre. Contre toi. Poétique, non ?' },
  ],
  // BIG BOSS — le Chat Militaire (Boss Final)
  militaire: [
    { cat: 'Un chat en treillis ? Sérieux ?', boss: 'Silence, recrue. Ici, c’est MON champ de bataille.' },
    { cat: 'T’as un bandana et tout. Trop stylé.', boss: 'Ce bandana a vu cent guerres. Tu ne verras pas la fin de celle-ci.' },
    { cat: 'Des mines ? T’as pas confiance.', boss: 'La confiance se mérite. La tienne explosera.' },
    { cat: 'Missile Prédator ? T’en fais des tonnes.', boss: 'J’en fais juste assez pour t’effacer.' },
    { cat: 'Tu invoques les autres boss ? Triche !', boss: 'À la guerre, tout est permis, soldat.' },
    { cat: 'Des tourelles, des tanks… t’as peur ?', boss: 'Je suis méthodique. Toi, tu es fini.' },
    { cat: 'On peut négocier autour de croquettes ?', boss: 'Négociation refusée. Ouverture du feu.' },
    { cat: 'Neuf vies contre une armée. Équilibré.', boss: 'Aucune de tes vies ne quittera cette base.' },
    { cat: 'T’es le dernier ? Ça se fête !', boss: 'Ça se termine. Par toi. Ici. Maintenant.' },
    { cat: 'Salut militaire, adieu militaire.', boss: 'Repos éternel, chaton. Grade : cible.' },
  ],
};
